# Generated by Django 4.2.1 on 2024-05-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthPrediction', '0003_alter_patientprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
