# Generated by Django 4.2.1 on 2024-05-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthPrediction', '0004_doctorprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default=('MALE', 'Male'), max_length=10),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty',
            field=models.CharField(choices=[('Umum', 'Umum'), ('Anak', 'Anak'), ('Kulit', 'Kulit'), ('Penyakit Dalam', 'Penyakit Dalam'), ('Psikiater', 'Psikiater'), ('Kandungan', 'Kandungan'), ('Hewan', 'Hewan'), ('Psikolog Klinis', 'Psikolog Klinis'), ('THT', 'THT'), ('Urologi', 'Urologi'), ('Andrologi', 'Andrologi'), ('Jiwa', 'Jiwa'), ('Gizi', 'Gizi'), ('Paru', 'Paru'), ('Gigi', 'Gigi'), ('Bedah', 'Bedah'), ('Saraf', 'Saraf'), ('Jantung', 'Jantung'), ('Konselor Laktasi', 'Konselor Laktasi'), ('Kandungan', 'Kandungan'), ('Mata', 'Mata'), ('Fisioterapi', 'Fisioterapi'), ('Bidan', 'Bidan')], default=('Umum', 'Umum'), max_length=50),
        ),
    ]
