# Generated by Django 4.2.1 on 2024-05-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthPrediction', '0008_remove_pharmacistprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('PHARMACIST', 'Pharmacist')], default='ADMIN', max_length=50),
        ),
    ]
