# Generated by Django 4.2.1 on 2024-05-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthPrediction', '0010_medicine_order_purchaserequest_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
