# Generated by Django 4.2.1 on 2024-06-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthPrediction', '0013_alter_medicalhistory_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
